# Generated by Django 4.1.4 on 2022-12-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('running_interval', models.CharField(choices=[('one_min', '1 min'), ('five_min', '5 min'), ('one_hour', '1 hour'), ('two_hour', '2 hour'), ('three_hour', '3 hour'), ('four_hour', '4 hour'), ('one_day', '1 day')], max_length=15)),
                ('settings', models.TextField(max_length=10000)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
