# Generated by Django 4.1.4 on 2022-12-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('running_interval', models.CharField(choices=[('one_min', '1 min'), ('five_min', '5 min'), ('one_hour', '1 hour'), ('two_hour', '2 hour'), ('three_hour', '3 hour'), ('four_hour', '4 hour'), ('one_day', '1 day')], db_index=True, max_length=15)),
                ('settings', models.TextField(max_length=10000)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.IntegerField(choices=[(0, '{"name": "5", "timestamp": 300}'), (1, '{"name": "15", "timestamp": 4500}'), (2, '{"name": "30", "timestamp": 1800}'), (3, '{"name": "60", "timestamp": 3600}'), (4, '{"name": "120", "timestamp": 7200}'), (5, '{"name": "180", "timestamp": 10800}'), (6, '{"name": "240", "timestamp": 14400}'), (7, '{"name": "1D", "timestamp": 86400}'), (8, '{"name": "1W", "timestamp": 604800}')], db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
