# Generated by Django 4.1.4 on 2023-01-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('crontab_code', models.CharField(db_index=True, max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.IntegerField(choices=[(0, '{"name": "5", "timestamp": 300}'), (1, '{"name": "15", "timestamp": 4500}'), (2, '{"name": "30", "timestamp": 1800}'), (3, '{"name": "60", "timestamp": 3600}'), (4, '{"name": "120", "timestamp": 7200}'), (5, '{"name": "180", "timestamp": 10800}'), (6, '{"name": "240", "timestamp": 14400}'), (7, '{"name": "1D", "timestamp": 86400}'), (8, '{"name": "1W", "timestamp": 604800}')], db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('base_capital', models.IntegerField(default=100)),
                ('pine_id', models.CharField(max_length=64)),
                ('pine_version', models.CharField(max_length=7)),
                ('script_mode', models.CharField(choices=[('strategy', 'strategy'), ('indicator', 'indicator')], default='indicator', max_length=20)),
                ('telegram_id', models.CharField(max_length=20)),
                ('broker_is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
