# Generated by Django 4.1.4 on 2023-03-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_tradingviewstrategy_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewstrategy',
            name='broker',
            field=models.IntegerField(choices=[(0, 'binance')], db_index=True, default=0),
        ),
    ]
