# Generated by Django 4.1.4 on 2023-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_tradingviewstrategy_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewstrategy',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradingviewstrategy',
            name='margin_type',
            field=models.IntegerField(choices=[(0, 'ISOLATED'), (1, 'CROSSED')], db_index=True, default=0),
        ),
    ]
