# Generated by Django 4.1.4 on 2023-03-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_tradingviewstrategy_leverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingviewstrategy',
            name='chart_type',
        ),
    ]
