# Generated by Django 4.1.4 on 2023-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_remove_tradingviewstrategy_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewstrategy',
            name='strategy_model',
            field=models.JSONField(default=dict, help_text='you can add bellow keys\n  open_position_value\n   close_position_value\n   take_profit_value\nuse like this format {"1": "open_position_value"} \nif has many use number in key'),
        ),
    ]
