version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.10
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=KN4CsdRe5slkps3hdvwQb
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
    networks:
      - services_handler_net

  postgres_db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "JPmb@3q1b31mV21FmCx"
      POSTGRES_DB: strategy_manager
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/
      - ./db_data:/var/lib/postgresql/data
    networks:
      - services_handler_net

  pgadmin4_ui:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: '3q1b31mV21FmCx'
      PGADMIN_DEFAULT_EMAIL: 'lirezazadeh77@gmail.com'
    volumes:
      - './pgadmin4:/pgadmin4'
    ports:
      - '8000:80'
    networks:
      - services_handler_net

volumes:
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/rabbitmq
      o: bind

networks:
  services_handler_net:
    external: true

