# Generated by Django 4.1.4 on 2023-03-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('position_type', models.IntegerField(choices=[(0, 'limit'), (1, 'market'), (2, 'stop'), (3, 'take profit'), (4, 'stop market'), (5, 'take profit market'), (6, 'trailing stop market')], db_index=True)),
                ('position_side', models.IntegerField(choices=[(0, 'long'), (1, 'short')], db_index=True)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('candle_datetime', models.DateTimeField()),
                ('start_send_to_broker_datetime', models.DateTimeField()),
                ('end_send_to_broker_datetime', models.DateTimeField()),
                ('broker', models.IntegerField(choices=[(0, 'binance')], db_index=True)),
                ('broker_response_status_code', models.IntegerField()),
                ('broker_response_message', models.TextField(null=True)),
                ('request_from', models.CharField(max_length=50)),
                ('request_id', models.IntegerField()),
                ('position_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_position', to='broker_manager.positionmanager')),
            ],
        ),
    ]
