# Generated by Django 4.1.4 on 2023-01-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_dynamic_schedule', '0002_alter_celerydynamicschedule_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celerydynamicschedule',
            old_name='task_kwargs',
            new_name='task_args',
        ),
    ]
